### ISSUE TITLE
[chart] blurred text

### ISSUE THREAD

**Issue by roccomuso** [rajgoel/reveal.js-plugins#5] opened 2016-03-11 23:15 UTC
Why in the Chart Demo, texts are blurred?

**Comment by rajgoel** [comment] 2016-03-12 08:34
This is probably related to scaling: the chart is created for some resolution and reveal.js changes the resolution to fit to the screen size. 

I haven't seen the blur. Are you using a very large screen?

**Comment by roccomuso** [comment] 2016-03-12 15:18
My screen is a 22" and my resolution is 1920x1080. It's not that big i guess.

**Comment by rajgoel** [comment] 2016-03-17 08:34
You might want to play around width and height of the [Reveal.js configuration](https://github.com/hakimel/reveal.js#presentation-size) or explicitly set it for the ```canvas``` element. In the demo I used ```class="stretch"``` which might cause the problem you have.

**Comment by rajgoel** [comment] 2016-04-10 09:56
Closing this for now because I cannot reproduce this problem. Please feel free to reopen this issue and provide a minimal example allowing to reproduce the problem.

**Closed by rajgoel** 2016-04-10 09:56 UTC

**Comment by bunopus** [comment] 2016-10-19 21:40
I have the same problem. I am using Chrome 54, on Ubuntu 15.04. Strange, but for example this plugin (https://dvenkatsagar.github.io/prez/reveal-chart.html#/) looks fine

**Comment by rajgoel** [comment] 2016-10-20 07:47
@bunopus Can you provide a screenshot illustrating the issue?

**Comment by bunopus** [comment] 2016-10-20 20:16
For this plugin
![blurry](https://cloud.githubusercontent.com/assets/9258200/19576159/a2c12cc6-971a-11e6-88f9-f59bb4b36094.png)

For another plugin (https://dvenkatsagar.github.io/prez/reveal-chart.html#/)
![another_plugin](https://cloud.githubusercontent.com/assets/9258200/19576191/bb1e2f6c-971a-11e6-8af5-94d0e6c999ee.png)

Maybe it is not so noticeable in screenshots, but on the big tv it is really annoying. I think it maybe Chart.js itself, because reveal-chart plugin uses Chart v1.

**Comment by rajgoel** [comment] 2016-10-21 07:43
Sorry, I don't really see a real difference, but this might also be related to my eyes or my screen ;-)

I can think of the following reasons/remedies for a "blurry" text:

1) Reduce the contrast of the label color to the background color, because white text on black background is not so easy to render beautifully as a gray text on black background.
2) As noted above make sure that there is as little as possible scaling (reveal.js may scale and so may chart.js)
3) It may be that chart.js renders differently in v1 compared to v2. 

In all three cases there is nothing much that can be done in the code of this plugin. In fact, the plugin is just a wrapper to use reveal.js and chart.js (just like the other plugin you mentioned https://gitlab.com/dvenkatsagar/reveal-chart).

**Comment by bunopus** [comment] 2016-10-25 21:55
@rajgoel i`ve discovered, that not only picture is blurred, but canvas is not clickable! So i can`t click on legend and switch charts (first screenshot).
This is not triggered by plugin, because if i set
```
  minScale: 1,
  maxScale: 1
```
in reveal.js config - problem will disappears. So this is in reveal or chart.js itself. Anyway thanks for help.

**Comment by rajgoel** [comment] 2016-10-26 15:52
Sounds like a scaling issue. Sometimes mouse coordinates get messed up when an element is scaled. Did you try using the latest chart.js v2.3? This might help with the clicking issue.



-------- Ursprüngliche Nachricht --------
Von: Evgeny Gusev <notifications@github.com> 
Datum:25.10.2016  23:55  (GMT+01:00) 
An: "rajgoel/reveal.js-plugins" <reveal.js-plugins@noreply.github.com> 
Cc: Asvin Goel <github@telematique.eu>, Mention <mention@noreply.github.com> 
Betreff: Re: [rajgoel/reveal.js-plugins] [chart] blurred text (#5) 

@rajgoel ive discovered, that not only picture is blurred, but canvas is not clickable! So i cant click on legend and switch charts (first screenshot).
This is not triggered by plugin, because if i set

  minScale: 1,
  maxScale: 1
in reveal.js config - problem will disappears. So this is in reveal or chart.js itself. Anyway thanks for help.

**Comment by rajgoel** [comment] 2017-01-30 13:17
I guess this issue https://github.com/chartjs/Chart.js/issues/2814 is related
