### ISSUE TITLE
Chalkboard does not work when width and height are set

### ISSUE THREAD

**Issue by clayms** [rajgoel/reveal.js-plugins#109] opened 2021-02-03 20:02 UTC
When I include the following in the YAML header of my markdown file:

```
width: \"100%\"
height: \"70%\"
```

The following issues occur:
1. The chalkboard grid will not display,
2. I cannot draw on the chalkboard.

If I comment out those two lines in the YAML header, all functionality is restored.

**Comment by rajgoel** [comment] 2021-04-16 11:42
Duplicate of #104

**Closed by rajgoel** 2021-04-16 11:42 UTC
Labels: duplicate
