### ISSUE TITLE
[animate] Arrow end markers in SVG don't show in animate module

### ISSUE THREAD

**Issue by TS-CUBED** [rajgoel/reveal.js-plugins#151] opened 2022-09-11 16:29 UTC
I am trying to create an animation with SVGs created in Inkscape.

The generated (simplified for this bug report) SVG looks like:

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Created with Inkscape (http://www.inkscape.org/) -->

<svg
   width="210mm"
   height="297mm"
   viewBox="0 0 210 297"
   version="1.1"
   id="svg5"
   inkscape:version="1.2.1 (9c6d41e410, 2022-07-14)"
   sodipodi:docname="drawing.svg"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:svg="http://www.w3.org/2000/svg">
  <defs
     id="defs2">
    <marker
       style="overflow:visible"
       id="marker2419"
       refX="0"
       refY="0"
       orient="auto-start-reverse"
       inkscape:stockid="Arrow1L"
       markerWidth="8.75"
       markerHeight="5"
       viewBox="0 0 8.75 5"
       inkscape:isstock="true"
       inkscape:collect="always"
       preserveAspectRatio="xMidYMid">
      <path
         style="fill:context-stroke;fill-rule:evenodd;stroke:none"
         d="M 0,0 5,-5 -12.5,0 5,5 Z"
         id="path2417"
         transform="scale(-0.5)" />
    </marker>
    <marker
       style="overflow:visible"
       id="Arrow1L"
       refX="0"
       refY="0"
       orient="auto-start-reverse"
       inkscape:stockid="Arrow1L"
       markerWidth="8.75"
       markerHeight="5"
       viewBox="0 0 8.75 5"
       inkscape:isstock="true"
       inkscape:collect="always"
       preserveAspectRatio="xMidYMid">
      <path
         style="fill:context-stroke;fill-rule:evenodd;stroke:none"
         d="M 0,0 5,-5 -12.5,0 5,5 Z"
         id="arrow1L"
         transform="scale(-0.5)" />
    </marker>
  </defs>
  <g
     inkscape:label="Layer 1"
     inkscape:groupmode="layer"
     id="layer1">
    <path
       style="fill:none;stroke:#000000;stroke-width:1.32291667;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1;marker-start:url(#marker2419);marker-end:url(#Arrow1L);stroke-dasharray:none"
       d="M 149.65406,65.310702 C 36.4915,44.26418 36.4915,44.26418 36.4915,44.26418"
       id="path2349" />
  </g>
</svg>
```

Using:

```
<div data-animate data-src="images/drawing.svg"></div>
```

the displayed SVG does not show the arrow start and end markers. They do show OK in all other SVG viewers and I can't see a problem in the SVG file itself.

Is this a known problem with either animate or SVG.js? I can create all the animation I need with the actual SVG I am working with, but all the vectors do not show any arrow markers.

**Comment by rajgoel** [comment] 2022-09-11 17:44
This problem could be caused by the use of namespaces in svg and the fact that reveal.js hides all slides except the current. See: https://stackoverflow.com/questions/54349169/svg-marker-disappears-when-svg-with-identical-definition-is-hidden
It is unlikely that this can be fixed by the plugin, but any advise would be appreciated.

**Comment by TS-CUBED** [comment] 2022-09-11 18:06
That would explain it if there were another svg in the file. But this is the only one. So no SVG should be hidden when this one is displayed.

**Comment by rajgoel** [comment] 2022-09-11 18:53
Did you try copying the svg code into the html to see whether the markers show without using the plugin?

**Comment by TS-CUBED** [comment] 2022-09-11 21:51
Yes, I have now included the raw SVG on a separete slide, and it's the same then.

**Comment by rajgoel** [comment] 2022-09-12 08:38
Arrow markers should work in general and I have used them successfully (with the above mentioned problems on namespacing). If your SVG doesn't show properly, it may be the SVG itself, the browser, or anything else. I'm closing this issue as it is probably not caused by the plugin. Please feel free to post a solution, should you find one to help others bumping into the same issue.

**Closed by rajgoel** 2022-09-12 08:38 UTC

**Comment by TS-CUBED** [comment] 2022-09-12 09:47
It is indeed a problem with firefox. It's the same with directly putting the SVG into HTML. 

The markers do show up in Chrome. However, there they do not change color with the path they belong to and all show up in black.

This whole SVG business seems to be much less mature than I'd hoped :-(
