### ISSUE TITLE
Seminar+chalkboard bug: twitchy behavior

### ISSUE THREAD

**Issue by edemaine** [rajgoel/reveal.js-plugins#128] opened 2021-08-09 13:55 UTC
Reproduction:
* Open two copies of https://rajgoel.github.io/reveal.js-demos/seminar-demo.html?room=ROOM_NAME in two browsers
* Become host in both
* Draw some annotation on one
* Press DELETE to erase that annotation
* Try changing slides
* Slide transitions twitch back and forth

The tabs seem to be competing for which slide to show. Closing either tab stops the problem.

A workaround for now is to use BACKSPACE (delete *all* annotations). That does not seem to cause the bug.

**Comment by rajgoel** [comment] 2021-08-09 14:10
'DEL',and 'BACKSPACE' are not considered in the synchronisation, they are more of a possibility to clean up the storage of previous drawings. Clearing the canvas by pressing '+' should work though. Need to clarify this in documentaation.

**Comment by rajgoel** [comment] 2021-08-09 14:14
Not sure whether 'DEL',and 'BACKSPACE' synchronisation can be supported easily without side effects, but I should take a look at this as well.

**Comment by edemaine** [comment] 2021-08-09 14:17
Somehow BACKSPACE does work.  I couldn't get `+` to do anything.  To clarify, I'm talking about slide annotation, not chalkboard (but `+` doesn't seem to do anything in either case).

Maybe we should add a warning to the DELETE popup (and possibly the BACKSPACE) popup, when in seminar mode?

**Comment by rajgoel** [comment] 2021-08-09 14:27
If '+' doesn't do anything, the shortcut is probably deactivated or overwritten. There used to be a keyboard option clash with older versions of the audio slideshow plugin that should be resolved by 6b2251b0fe79fb0be6631f9b898c85463121ffbe (may be the commit has not made its way into the latest release). Pressing '?' should show all keyboard shortcuts, when I'm on https://rajgoel.github.io/reveal.js-demos/seminar-demo.html it shows  "+ | Clear drawings on slide" and it works both on chalkboard and slide canvas.

**Comment by rajgoel** [comment] 2021-08-09 14:31
Indeed, https://github.com/rajgoel/reveal.js-plugins/commit/6b2251b0fe79fb0be6631f9b898c85463121ffbe has not made it into the latest release. Probably I will collect a few more issues and improvements to the docs before creating a new release.

**Comment by edemaine** [comment] 2021-08-09 14:31
Thanks, I didn't know about `?`!  I also get `+` listed correctly, but the key doesn't work in Chrome or Firefox, on Windows 10, as neither <kbd>Shift</kbd>+<kbd>=</kbd> nor <kbd>Gray +</kbd>.  Weird.

**Comment by rajgoel** [comment] 2021-08-09 14:40
Ok, that may be related to the QWERTY keyboard, I use a QWERTZ keyboard and haven't thought about the need to press  <kbd>Shift</kbd>+<kbd>=</kbd>  on QWERTY. The easiest instant fix for you should be to change the `keyCode` on https://github.com/rajgoel/reveal.js-plugins/blob/master/chalkboard/plugin.js#L93 . Need to figure out a proper fix for <kbd>Shift</kbd>+<kbd>=</kbd> to work or change the default key.

**Comment by edemaine** [comment] 2021-08-09 14:46
Ah, I guess this is why `keyCode` is deprecated. :-) Indeed, on my QWERTY keyboard, <kbd>Shift</kbd>+<kbd>=</kbd> has keycode 187, same as <kbd>=</kbd>, and<kbd>Gray +</kbd> has keycode 107.  It's a shame that RevealJS relies on `keyCode`, but that's probably an issue for a different issue/PR on their repo.

Would you be interested in a PR that adds behavior to the 187 keycode (in addition to existing 171)?  This would probably make it appear twice in `?` unfortunately...

**Comment by rajgoel** [comment] 2021-08-09 14:51
I guess reaching out to RevealJS first might be the better choice to not pollute the key-bindings too much.

**Comment by edemaine** [comment] 2021-08-09 14:52
I opened https://github.com/hakimel/reveal.js/issues/2993

**Comment by rajgoel** [comment] 2021-08-09 15:00
Many thanks! :clap:

**Comment by rajgoel** [comment] 2021-08-09 15:04
Another possibility would be to add
```js
document.addEventListener('keypress', function(event) { if (event.key == "+" ) RevealChalkboard.clear();} );
```
to your presentation.

This should work on any keyboard layout.

**Comment by edemaine** [comment] 2021-08-09 16:18
I've run into some more twitchy behavior with multiple hosts:
1. In some scenarios, the slide number seems to get desynchronized between two hosts, and the shown slide blinks repeatedly forever (until someone reloads). I'm not quite sure what the triggers were, but it happened multiple times without fancy operations like Backspace/Delete. I'll let you know if I can come up with more reproductions, but it might be nice to figure out the borked state the pair of hosts are getting into (e.g. from Delete key) so that they can stop fighting for which slide is visible.
2. When one user is annotating and the other user moves their mouse (simultaneously), annotations act very messy. We get lots of straight lines, probably between our two mouse positions. And the up/down state of our mouse seems to get messed up, so the drawing user is often still drawing even after they release the mouse button.  (Fix is to click and release mouse again.)  I don't necessarily expect two simultaneous annotations to work, but it's pretty hard to use when accidental mouse movements by a user not drawing causes the drawing user to break down.

I didn't see either of these as one user testing in two browser windows, but it was quite easy with two users simultaneously interacting on separate computers. Happy to help debug further.

**Comment by rajgoel** [comment] 2021-08-10 11:14
Apparently concurrency in multi-host settings is more complicated than I originally hoped. I just created a new branch `concurrency` and tried to fix the issues with simultaneous drawings. I hope this works now. Would be great if you could confirm the fix.

Will look at the issue with the slide changes asap. I guess the problem resides with user A and B changing slides simultaneously without having received the status update from the other user and thus the result becomes inconsistent.

**Comment by rajgoel** [comment] 2021-08-10 13:39
I hope the back and forth slide changes are now fixed in the `concurrency` branch.

**Comment by edemaine** [comment] 2021-08-10 14:28
Wow, that was fast!  I just did tested 9fda82766c3c1c0c9a4b5d979418afe077d88cb0 a bunch, and it is *much* improved.  On the plus side:
* I haven't been able to been able to reproduce flickering of slide numbers, e.g. when we both simultaneously advance slides.
* Two users can draw simultaneously (or move our mouse) and we both see all the strokes, without lines connecting our strokes. (If one user changes the color, it affects the other user still drawing, but that is at least a reasonable interpretation of intent.)

I still found some buggy behavior. I think maybe you fixed the live updates, but haven't fixed the store yet? It would be consistent with this behavior.
* If two hosts draw simultaneously, and then I cause the slide to refresh, by resizing the window or leaving and returning to the slide, then our drawings get connected by lots of long lines.  I don't think it happens anymore when one user is just moving their mouse, though.
* If I draw an annotation, then the other host draws an annotation, and then I cause the slide to refresh, I still see my stroke but not the other host's stroke. Conversely, they see their stroke and not my stroke.
* Probably less important, but <kbd>Delete</kbd> still causes weird behavior, but it's at least less twitchy.  The screen clears on both sides, but neither of us can then change slides; any attempt to do so returns to the slide that was cleared.  Reloading fixes the problem.

Hope this helps diagnose!  Let me know if you need a human testing buddy and we can schedule a time.

**Comment by rajgoel** [comment] 2021-08-10 15:07
Many thanks again for the feedback and tests. 

>     If two hosts draw simultaneously, and then I cause the slide to refresh, by resizing the window or leaving and returning to the slide, then our drawings get connected by lots of long lines. I don't think it happens anymore when one user is just moving their mouse, though.

Need to check what is going wrong here. Resizing causes the canvas to redraw and it looks like there might be an issue in calculating the coordinates. 


>    If I draw an annotation, then the other host draws an annotation, and then I cause the slide to refresh, I still see my stroke but not the other host's stroke. Conversely, they see their stroke and not my stroke.

That's true for the moment. Storage for concurrent annotations didn't work well and I temporarily turned it off. A fix for this is already on my todo list.

>    If I draw on one slide in one color, change slides, both users draw in various colors, and return to the original slide, the color of the annotations has sometimes changed color.

For some inconsistencies, I currently do not know how to fix them best with the current architecture. In particular, simultaneous and contradictory events like color changes are a problem. I'll probably add color information to message updates and storage. 
 
>    Probably less important, but Delete still causes weird behavior, but it's at least less twitchy. The screen clears on both sides, but neither of us can then change slides; any attempt to do so returns to the slide that was cleared. Reloading fixes the problem.

I will probably switch the keybindings to have 'DEL' behave to clear the canvas and 'BACKSPACE' to reset the storage. Storage operations should not be used in a running seminar.

> Hope this helps diagnose! Let me know if you need a human testing buddy and we can schedule a time.

Yes, this helps very much! Big thanks for your offer to assist in testing. Might come back to you as soon as I have made progress on those issues that I already have on my list.

**Comment by rajgoel** [comment] 2021-08-12 10:06
I have rewritten event handling https://github.com/rajgoel/reveal.js-plugins/commit/ae06668bbb3e2ee873a970e23d1a5d9d38cd8e0b and now all curve segment should have all the information to be drawn without relying on the prior state. Hopefully, most of above issues are gone with this and the number of regressions is small. With the rewrite, prior drawings are no longer compatible. To be on the safe side, please make sure to delete all prior drawings that still might be in local storage by pressing <kbd>BACKSPACE</kbd>.

Also I changed the default keybindings in https://github.com/rajgoel/reveal.js-plugins/commit/345d0fff64dae7070b4d812bf0ebf18eef4757df. Now <kbd>DEL</kbd> is used to clear the canvas and resetting a single slide is no longer available by default (I guess there aren't many use cases for this anyhow).  I fixed a few bugs that should now allow to broadcast <kbd>BACKSPACE</kbd> (i.e. reset the entire storage) and that prevent infinite event loops for clearing slides.

May be you can have a quick look whether you notice any immediate bugs, and then we could schedule a time to test and discuss further issues next week.

**Closed** 2023-09-14 19:57 UTC
